### ISSUE TITLE
what's your reference code ?

### ISSUE THREAD

**Issue by sk8xiao** [azinke/mmwave#1]
Is this repository the code of reference ti?
where i can find your reference?

**Comment by azinke** [comment]
When you install MMWAVE STUDIO (that can be downloaded from TI's website), you'll have access to some example C codes in the installation folder. Those examples have been used in the implementation in this repo. And the `mmwavelink` is the same as provided by TI (also available in the installation folder of mmwave studio). Did I get your question right?!

**Comment by azinke** [comment]
I'll close this issue for now. If there are further questions, please feel free to re-open the issue. Thanks!
