### ISSUE TITLE
Can not capture any data with MMWCAS-RF-EVM (AWR1243)

### ISSUE THREAD

**Issue by kangk906** [azinke/mmwave#5]
Thanks for your repository! 

I have the MMWCAS-RF-EVM with AWR1243 so I replaced the 2243 firmware with the 1243 firmware downloaded from TI. Other files were not changed. All scripts run successfully on the machine, however, when I check the folder and find the no data is captured. 

Do I have to modify other scripts? Thanks!

**Comment by azinke** [comment]
Hi @kangk906 !
I haven't tested with the 1243 yet. But the same issue happens sometimes with the 2243 as well. I cannot tell exactly what is the cause (synch issue, power supply, etc.) But rebooting the board and trying to gain work for the 2243. Try that and see how it goes.

**NOTE:**  Make sure that the power supply has the recommended voltage and well regulated (this was one of my assumptions but I'm not sure if it's actually the cause)
