### ISSUE TITLE
How to process the bin file?

### ISSUE THREAD

**Issue by deltaRing** [azinke/mmwave#7]
Dear azinke,
Do you have any example or tutorial to process the default config of radar bin file? I would appreciate if there's any example.

**Comment by deltaRing** [comment]
because there's no json file to describe the components of the bin file, i am researching your another project which can parse the bin file into individual frame.

**Comment by azinke** [comment]
Hi @deltaRing ,
Indeed the project https://github.com/azinke/mmwave-repack.git provides an example code of how the `.bin` binary files can be parsed.

The lines highlighted by the link below describe how the files are packaged together 
https://github.com/azinke/mmwave-repack/blob/ff6e361ba2f37dbe8403dbade59c569d81f1af36/repack.py#L21-L61

**Comment by deltaRing** [comment]
> Hi @deltaRing , Indeed the project https://github.com/azinke/mmwave-repack.git provides an example code of how the `.bin` binary files can be parsed.
> 
> The lines highlighted by the link below describe how the files are packaged together https://github.com/azinke/mmwave-repack/blob/ff6e361ba2f37dbe8403dbade59c569d81f1af36/repack.py#L21-L61

much appreciate your help, i have already processed the bin file based your project :))))

it works really great,  and i have remixed a ROS version based on your project.

**Comment by azinke** [comment]
Awesome!
